### ISSUE TITLE
Stuck on "Validating cluster..." in AWS

### ISSUE THREAD

**Issue by gamache** [hydro-project/cluster#4]
Hello! I'm trying to set up a cluster on AWS (using the updated instructions in #3) and the install hangs (24+ hours) here:

```
$ python3 -m hydro.cluster.create_cluster -m 1 -r 1 -f 1 -s 1
Creating cluster object...
Adding general instance group
Creating cluster on AWS...
Validating cluster...
```

I don't see anything having been created in EC2 or Route53. The AWS access key ID and secret are set properly and point to a user with adequate permissions.

Can you provide some guidance?  I'm happy to debug this further.

Thanks!

**Comment by gamache** [comment]
Here's what I get when I Ctrl-C it:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/hydro-project/cluster/hydro/cluster/create_cluster.py", line 205, in <module>
    aws_key_id, aws_key)
  File "/home/ubuntu/hydro-project/cluster/hydro/cluster/create_cluster.py", line 39, in create_cluster
    ssh_key])
  File "/home/ubuntu/hydro-project/cluster/hydro/shared/util.py", line 63, in run_process
    subprocess.run(command, cwd='hydro/cluster/kops', check=True)
  File "/usr/lib/python3.6/subprocess.py", line 425, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.6/subprocess.py", line 855, in communicate
    self.wait()
  File "/usr/lib/python3.6/subprocess.py", line 1477, in wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.6/subprocess.py", line 1424, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
```

**Comment by vsreekanti** [comment]
Hi @gamache -- in the past, when I've set up new users to run these scripts, I've found that the default kops permissions that their getting started asks you to use are insufficient. The simplest fix that I have found is adding `AdministratorAccess` to the user generally will make the `create_cluster` script run successfully. 

If that's not an option for you, I'd be happy to work with you to figure out what exactly needs to change. Unfortunately, I haven't had the time to debug exactly why there's this mismatch, so I don't have a canned solution..

**Comment by gamache** [comment]
I should have been more clear -- I am already using a user with AdministratorAccess.

**Comment by vsreekanti** [comment]
Got it. Can you run this manually, and see what it outputs?

```bash
kops create cluster --master-size c4.large --zones us-east-1a --ssh-public-key ${SSH_KEY}.pub ${HYDRO_CLUSTER_NAME} --networking kube-router
```

**Comment by gamache** [comment]
Aha! That gave me a hint I needed -- SSH keys must be present on the VM to use Kops.  I created some with `ssh-keygen` and proceeded, then ran into a second issue.

Kops is apparently not respecting the AWS region I have configured in `~/.aws/config`, instead defaulting to us-east-1.  But now it's at least creating infrastructure, and I can see the ASGs when I switch regions to us-east-1 in my AWS console.

**Comment by vsreekanti** [comment]
Ah, that's actually an issue on our end -- we currently have `us-east-1a` hardcoded, which you can see in the `--zones` argument above. You can change that in L49 of the `create_cluster_object.sh` script ([link](https://github.com/hydro-project/cluster/blob/master/hydro/cluster/kops/create_cluster_object.sh#L49)).
